cpu: cpu_classifier.py
	python cpu_classifier.py 250
single: single_classifier.py
	python single_classifier.py 250
multi: multi_classifier.py
	python multi_classifier.py 250
clean:
	rm -r ./data
	rm ./outputs/cifar_net*
	rm ./outputs/*.png
